export const sampleResponse = {
  data: {
    address: "0x297F0458cDDa6a60116eaC648ed2419293131114",
    score: 0.25668482813999993,
    scoreType: 0,
    mintData: {
      signature:
        "0x06e7ca52bee6b9108455446360dd42dbe0779fc466166f8d08724955c2e2c614481c508492f49536ade8baa2ee3481960e6d4af408422ac0482d72ee1cad10201c",
      mintedScore: 2566,
      calculationModel: 10,
      deadline: 1689157544321,
      metadataUrl:
        "https://w3s.link/ipfs/bafkreidpnpahwomw7dec4vd5axetig53fpioditbwnjvvr7fgaqgqgonaq",
      chainId: 324,
      mintedChain: {
        isEnabled: true,
        chainId: 324,
        hexChainId: "0x144",
        chainName: "zkSync Era Mainnet",
        blockchainName: "zkSync Era Mainnet",
        blockchainSlug: "zksyncera",
        blockExplorerUrls: ["https://explorer.zksync.io/"],
        rpcUrls: ["https://zksync2-mainnet.zksync.io"],
        isEVMCompatible: true,
        sbtData: {
          Finance: {
            contractAddress: "0x00Ba30361E6e0E15da8a0595464bF38E4102797a",
            tokenName: "NMSS",
            version: "0.7",
          },
        },
        nativeCurrency: {
          id: "0x0000000000000000000000000000000000000000",
          symbol: "ETH",
          name: "Ethereum",
          decimals: "18",
          logoUri:
            "https://defiyield-static.s3.eu-central-1.amazonaws.com/eth/0x0000000000000000000000000000000000000000/coinmarketcap.webp",
        },
        order: 42,
        icon: "https://defiyield-static.s3.eu-central-1.amazonaws.com/chains/zksync.jpg",
        labelIcon:
          "https://defiyield-static.s3.eu-central-1.amazonaws.com/chains/zksync_label.png",
        isHided: false,
        type: 1,
        platformIds: { Coingecko: "ethereum", DefiLLama: "era" },
        oracles: null,
      },
    },
    referralCode: "BucKrrxeix",
    stats: {
      noData: false,
      nativeBalance: 0.0029967,
      nativeBalanceUSD: 5.654503197,
      holdTokensBalanceUSD: 0,
      walletTurnover: 0.0029967,
      walletTurnoverUSD: 5.654503197,
      balanceChangeInLastMonth: 0.0029967,
      balanceChangeInLastYear: 0.0029967,
      walletAge: 1,
      totalTransactions: 0,
      totalRejectedTransactions: 0,
      averageTransactionTime: 0,
      maxTransactionTime: 0,
      minTransactionTime: 0,
      timeFromLastTransaction: 0,
      lastMonthTransactions: 0,
      lastYearTransactions: 0,
      transactionsPerMonth: 0,
      tokensHolding: 0,
      nativeToken: "ETH",
      nftHolding: 0,
      nftTrading: 0.0,
      nftWorth: 0,
      turnoverIntervals: [
        {
          startDate: "2023-07-11T11:37:36.618Z",
          endDate: "2023-08-11T11:37:36.618Z",
          amountSumValue: 0.0029967,
          amountOutSumValue: 0.0,
          amountInSumValue: 0.0029967,
          count: 1,
        },
      ],
      statsDescriptions: {
        NftHolding: {
          label: "Nft holding",
          description: "Total NFTs on wallet",
          units: "number",
        },
        NftTrading: {
          label: "Nft trading",
          description: "NFT trading activity",
          units: "ETH",
        },
        NftWorth: {
          label: "Nft worth",
          description: "NFT worth on wallet",
          units: "ETH",
        },
        NativeBalance: {
          label: "Native balance",
          description: "Wallet native token balance",
          units: "ETH",
        },
        NativeBalanceUSD: {
          label: "Native balance USD",
          description: "Wallet native token balance",
          units: "USD",
        },
        HoldTokensBalanceUSD: {
          label: "Hold tokens balance USD",
          description: "Wallet hold tokens total balance",
          units: "USD",
        },
        WalletTurnover: {
          label: "Wallet turnover",
          description: "The movement of funds on the wallet",
          units: "ETH",
        },
        WalletTurnoverUSD: {
          label: "Wallet turnover USD",
          description: "The movement of funds on the wallet",
          units: "USD",
        },
        BalanceChangeInLastMonth: {
          label: "Balance change in last month",
          description: "The balance change value in the last month",
          units: "ETH",
        },
        BalanceChangeInLastYear: {
          label: "Balance change in last year",
          description: "The balance change value in the last year",
          units: "ETH",
        },
        WalletAge: {
          label: "Wallet age",
          description: "Wallet age (from the first transaction)",
          units: "months",
        },
        TotalTransactions: {
          label: "Total transactions",
          description: "Total transactions on wallet",
          units: "number",
        },
        TotalRejectedTransactions: {
          label: "Total rejected transactions",
          description: "Total rejected transactions on wallet",
          units: "number",
        },
        AverageTransactionTime: {
          label: "Average transaction time",
          description: "Average time interval between transactions",
          units: "hours",
        },
        MaxTransactionTime: {
          label: "Max transaction time",
          description: "Maximum time interval between transactions",
          units: "hours",
        },
        MinTransactionTime: {
          label: "Min transaction time",
          description: "Minimal time interval between transactions",
          units: "hours",
        },
        TimeFromLastTransaction: {
          label: "Time from last transaction",
          description: "Time since last transaction",
          units: "months",
        },
        LastMonthTransactions: {
          label: "Last month transactions",
          description: "Last month transactions",
          units: "number",
        },
        LastYearTransactions: {
          label: "Last year transactions",
          description: "Last year transactions on wallet",
          units: "number",
        },
        TransactionsPerMonth: {
          label: "Transactions per month",
          description: "Average transaction per months",
          units: "number",
        },
        TokensHolding: {
          label: "Tokens holding",
          description: "Value of all holding tokens",
          units: "number",
        },
      },
    },
  },
  messages: [
    "Got soulbound token signature.",
    "Got zkSync Era Mainnet wallet Finance score.",
    "Can't create the Polygon ID claim.",
    "Successfully got referral wallet by address.",
    "There is no referral wallet with referral code lorem.",
  ],
  succeeded: true,
};
